%script pour effectuer un sondage

ui.SA = 0;
ui.HO = 0
ui.fig = figure;
ui.b1 = uicontrol('Position',[50,320,500,60],...
        'Style','Text',...
        'BackgroundColor', get (ui.fig, 'Color'),...
        'Fontsize', 20,...
        'String','Sondage Election: Selectionnez votre candidat');
    
ui.sarko = uicontrol('Position',[50,200,120,100],...
    'BackgroundColor',[0 0 1],...
    'String','Sarko',...
    'Fontsize',20,...
    'Callback', 'ui.SA = ui.SA + 1;');

ui.hollande= uicontrol('Position',[300,200,120,100],...
    'BackgroundColor',[1 0 0],...
    'String','Hollande',...
    'Fontsize',20,...
    'Callback', 'ui.HO = ui.HO + 1;calculateS;');

ui.result = uicontrol('Position',[200,100,100,50],...
    'BackgroundColor',[0 1 0],...
    'String','Result',...
    'Fontsize',20,...
    'Callback','calculateS;');

